"""empty message

Revision ID: 04e3286f4f7e
Revises: ef8f928739f6
Create Date: 2020-02-19 01:30:34.845916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04e3286f4f7e'
down_revision = 'ef8f928739f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('token', sa.String(length=30), nullable=False))
    op.add_column('token', sa.Column('token_hash', sa.String(length=100), nullable=False))
    op.drop_column('token', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('code', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('token', 'token_hash')
    op.drop_column('token', 'token')
    # ### end Alembic commands ###
