"""empty message

Revision ID: 1332a008fd97
Revises: e1fce7bdf577
Create Date: 2020-02-01 18:42:26.370889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1332a008fd97'
down_revision = 'e1fce7bdf577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_normal', sa.Column('data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_normal', 'data')
    # ### end Alembic commands ###
