"""empty message

Revision ID: 19e50ba68e73
Revises: 290e8bee439a
Create Date: 2020-02-09 17:00:39.906780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19e50ba68e73'
down_revision = '290e8bee439a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map', sa.Column('size_height', sa.Integer(), nullable=True))
    op.drop_column('map', 'size_hight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map', sa.Column('size_hight', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('map', 'size_height')
    # ### end Alembic commands ###
