"""empty message

Revision ID: 745117847f98
Revises: 1332a008fd97
Create Date: 2020-02-02 16:59:20.128969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '745117847f98'
down_revision = '1332a008fd97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('normal')
    op.add_column('card_normal', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_normal', 'create_time')
    op.create_table('normal',
    sa.Column('card_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('data', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('card_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
